# CI: lint, typecheck, tests.
# Runs on push to main (excluding docs) and pull requests.
# Chain: ci → build → deploy

when:
  - event: push
    branch: main
    path:
      exclude: ['*.md', '.claude/**']
  - event: pull_request
    branch: main
    path:
      exclude: ['*.md', '.claude/**']
  - event: manual

labels:
  backend: local

steps:
  - name: install
    image: bash
    commands:
      - uv sync --frozen

  - name: lint
    image: bash
    depends_on: [install]
    commands:
      - uv run ruff check app/ packages/sd-cli/sd_cli/
      - uv run ruff format --check app/ packages/sd-cli/sd_cli/
      - uv run mypy app/

  - name: test
    image: bash
    depends_on: [install]
    commands:
      - uv run pytest -v --tb=short

  - name: build-sd-cli
    image: bash
    depends_on: [install]
    commands:
      - cd packages/sd-cli && uv build
