# CI: lint, typecheck, tests.
# Runs on push to main (excluding docs) and pull requests.
# Chain: ci → build → deploy

when:
  - event: push
    branch: main
    path:
      exclude: ['*.md', '.claude/**']
  - event: pull_request
    branch: main
    path:
      exclude: ['*.md', '.claude/**']
  - event: manual

labels:
  backend: local

steps:
  - name: install
    image: bash
    environment:
      POETRY_VIRTUALENVS_PATH: /root/.cache/poetry-venvs
    commands:
      - find "$POETRY_VIRTUALENVS_PATH" -maxdepth 1 -mindepth 1 -type d -mtime +3 -exec rm -rf {} + 2>/dev/null || true
      - poetry install --no-interaction

  - name: lint
    image: bash
    depends_on: [install]
    environment:
      POETRY_VIRTUALENVS_PATH: /root/.cache/poetry-venvs
    commands:
      - poetry run ruff check app/
      - poetry run ruff format --check app/
      - poetry run mypy app/

  - name: test
    image: bash
    depends_on: [install]
    environment:
      POETRY_VIRTUALENVS_PATH: /root/.cache/poetry-venvs
    commands:
      - poetry run pytest -v --tb=short
