# Deploy: pull image and deploy to vm-gitea-runner-01.
# Runs after build passes on main branch pushes.
# Chain: ci → build → deploy
#
# Since the Woodpecker agent runs on the deploy target (local backend),
# docker commands execute directly — no SSH needed.

depends_on:
  - build

when:
  - event: push
    branch: main
    path:
      exclude: ['*.md', '.claude/**']

labels:
  backend: local

steps:
  - name: deploy
    image: bash
    environment:
      CI_GITEA_TOKEN:
        from_secret: ci_gitea_token
    commands:
      - SHORT_SHA=$(git rev-parse --short HEAD)
      - echo "=== Sprint-Dash Deployment ==="
      - 'echo "Image tag: $$SHORT_SHA"'

      # Login to Gitea registry (temp config to avoid credential persistence)
      - DOCKER_CONFIG_DIR=$(mktemp -d)
      - export DOCKER_CONFIG="$$DOCKER_CONFIG_DIR"
      - echo "$${CI_GITEA_TOKEN}" | docker login gitea.internal.kellgari.com.au -u singlis --password-stdin
      - trap "rm -rf $$DOCKER_CONFIG_DIR" EXIT

      # Pull new image
      - docker pull gitea.internal.kellgari.com.au/singlis/sprint-dash:$$SHORT_SHA

      # Stop old container (if exists)
      - docker stop sprint-dash 2>/dev/null || true
      - docker rm sprint-dash 2>/dev/null || true

      # Start new container
      - |
        docker run -d \
          --name sprint-dash \
          --restart unless-stopped \
          --env-file /opt/sprint-dash/.env \
          -p 8080:8080 \
          gitea.internal.kellgari.com.au/singlis/sprint-dash:$$SHORT_SHA

      - echo "Deployment triggered, waiting for health..."

      # Wait for health check
      - |
        for i in $(seq 1 15); do
          if curl -sf --connect-timeout 5 --max-time 10 http://localhost:8080/health; then
            echo ""
            echo "Sprint-dash is healthy"
            exit 0
          fi
          echo "Attempt $$i/15: waiting..."
          sleep 2
        done
        echo "Health check failed"
        exit 1
